CC = gcc
CFLAGS = -Wall -Werror -lm

SRCS = operating_system_system_signals main.c sin_cos/sincos.c
OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.h)

TARGET = program

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean